"""ehancing language model

Revision ID: 1e82d9b03d84
Revises: 91793886e808
Create Date: 2025-05-04 20:13:21.917791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1e82d9b03d84'
down_revision: Union[str, None] = '91793886e808'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('language', column_name="language", new_column_name="name", existing_type=sa.String, existing_nullable=False)
    op.add_column('language', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('language', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('language', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_language_created_at'), 'language', ['created_at'], unique=False)
    op.create_index(op.f('ix_language_updated_at'), 'language', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('language', column_name="name", new_column_name="language", existing_type=sa.String, existing_nullable=False, default="")
    op.drop_index(op.f('ix_language_updated_at'), table_name='language')
    op.drop_index(op.f('ix_language_created_at'), table_name='language')
    op.drop_column('language', 'updated_at')
    op.drop_column('language', 'created_at')
    op.drop_column('language', 'description')
    # ### end Alembic commands ###
