"""adding created_at and updated_at to aboutme table

Revision ID: 60cde4e765ed
Revises: a16996fdcc85
Create Date: 2025-07-30 11:27:44.791940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from datetime import datetime


# revision identifiers, used by Alembic.
revision: str = '60cde4e765ed'
down_revision: Union[str, None] = 'a16996fdcc85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aboutme', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.sql.func.now()))
    op.add_column('aboutme', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_aboutme_created_at'), 'aboutme', ['created_at'], unique=False)
    op.create_index(op.f('ix_aboutme_updated_at'), 'aboutme', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aboutme_updated_at'), table_name='aboutme')
    op.drop_index(op.f('ix_aboutme_created_at'), table_name='aboutme')
    op.drop_column('aboutme', 'updated_at')
    op.drop_column('aboutme', 'created_at')
    # ### end Alembic commands ###
