"""adding aboutme table

Revision ID: a16996fdcc85
Revises: d5c008cfd164
Create Date: 2025-07-30 10:45:29.360836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a16996fdcc85'
down_revision: Union[str, None] = 'd5c008cfd164'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aboutme',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('text2', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('language_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aboutme_id'), 'aboutme', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aboutme_id'), table_name='aboutme')
    op.drop_table('aboutme')
    # ### end Alembic commands ###
